### ISSUE TITLE
Unhandled error...

### ISSUE THREAD

**Issue by SebastienDevAccount** [kyleaa/homebridge-samsungtv2016#4]
Hi

On my Samsung TV, I got the following problem:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.0.10:8001
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

any idea?
Thanks
Séb

**Comment by roycepope** [comment]
I am getting this same error with a Samsung KS8000 (2016) :(

**Comment by kyleaa** [comment]
Merging this into #6
